site_name: Mvdef
site_author: Louis Maddox
site_description: >-
  Package providing command line tools to move/copy function/classes and their associated import statements between files.
site_url: https://mvdef.vercel.app
repo_name: lmmx/mvdef
repo_url: https://github.com/lmmx/mvdef
strict: true
watch: [src]

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2023- Louis Maddox

theme:
  name: material
  custom_dir: docs/theme
  palette:
    - scheme: default
      primary: white
  # logo: assets/images/logo-white.svg
  # favicon: assets/images/logo-black.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search
    - search.suggest
  font:
    text: Inter
    code: Source Code Pro

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lmmx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/permutans
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.definition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      noclasses: True
      pygments_style: lovelace
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/*/]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            line_length: 88 # default: 60
            # show_if_no_docstring: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_source: true
            show_submodules: true
            show_signature_annotations: true
  - search
  - section-index
  - social:
      cards_layout_options:
        color: #173a58

nav:
  - Home: index.md
  - Getting Started:
      - Getting Started: get_started.md
  - Reference:
      - reference/index.md
  - API:
      - api/index.md
      - api/cli.md
      - api/core.md
      - api/error_handling.md
      - api/legacy.md
      - api/log_utils.md
      - api/transfer.md
      - api/whitespace.md
