__all__ = ["help_text"]
help_text = (
    "usage: mvdef [-h] -m [MV ...] [-d] [-e] [-c] [-a] [-v] src dst\n"
    "\n"
    "\xa0\xa0Move function definitions from one file to another, moving/copying\n"
    "\xa0\xa0associated import statements along with them.\n"
    "\n"
    "\xa0 Option     Description                                Type (default)\n"
    "\xa0 —————————— —————————————————————————————————————————— ——————————————\n"
    "•\xa0src        source file to take definitions from       Path\n"
    "•\xa0dst        destination file (may not exist)           Path\n"
    "•\xa0mv         names to move from the source file         list of str\n"
    "•\xa0dry_run    whether to only preview the change diffs   bool (False)\n"
    "•\xa0escalate   whether to raise an error upon failure     bool (False)\n"
    "•\xa0cls_defs   whether to target only class definitions   bool (False)\n"
    "•\xa0all_defs   whether to target both class and funcdefs  bool (False)\n"
    "•\xa0verbose    whether to log anything                    bool (False)\n"
    "\n"
    "positional arguments:\n"
    "  src\n"
    "  dst\n"
    "\n"
    "options:\n"
    "  -h, --help            show this help message and exit\n"
    "  -m [MV ...], --mv [MV ...]\n"
    "  -d, --dry-run\n"
    "  -e, --escalate\n"
    "  -c, --cls-defs\n"
    "  -a, --all-defs\n"
    "  -v, --verbose"
)
